/**
@mainpage Common
@brief READ ME FIRST
@author Derek Smith

@section intro Introduction
These files are miscellaneous utility files, typically included with all applications. 
See the File List for documentation on each file.

@note Projects compiled with IAR Embedded Workbench for IAR version 4.21.2
 <hr>
@page about About this Documentation
This HTML output generated by Doxygen, a free documentation generator tool 
that uses special tags in the code to generate pretty HTML output that you see here. 
It is very similar to javadoc if you have experience with that, in fact many of the tags are the same. 
Documentation generators like this are highly recommended, especially if you're writing code that someone else will need to read.
@see www.doxygen.org

*/